Add main entrypoint for @docusaurus/core
Because the main entrypoint for `@docusaurus/core` is missing, if you run this:

```javascript
require('@docusaurus/core')
```

...you get an error:

```
> require('@docusaurus/core')
Uncaught Error: Cannot find module '@docusaurus/core'
```

If we add a main entrypoint, we get this instead:

```
{
  build: [Getter],
  clear: [Getter],
  deploy: [Getter],
  externalCommand: [Getter],
  serve: [Getter],
  start: [Getter],
  swizzle: [Getter],
  writeHeadingIds: [Getter],
  writeTranslations: [Getter]
}
```